sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 8.141.118.201
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDGrULGdBBeUK9nAvSm
    access-key-secret: su3JIAi83LdgyhuqwGcsmJ76KXGzzN
    bucket-name: sky-itcast-shuo
  wechat:
    appid: wxefcf0e1c84a7810e
    secret: 67e593d7b48ad5d63d8a59a08e6a0d1e
    mchid: 1707625139
    mchSerialNo: 2402222766F361019D684135FD3347A1F815447C
    privateKeyFilePath: C:\java\apiclient_key.pem
    apiV3Key: Yf133804353831770766266112345678
    weChatPayCertFilePath: C:\java\wechatpay_6FF64294A34E64F7C99FBE9C20DF022C99749775.pem
    notifyUrl: https://yuneyang.top/notify/paySuccess
    refundNotifyUrl: https://yuneyang.top/notify/refundSuccess


